[build]
  base = "/"
  publish = "/out"
  command = "npm run build"
  functions = "/netlify"

[build.environment]
  NEXT_SERVERLESS = "true"
  BUILD_LANGUAGES = "en-US,it-IT"
  BUILD_CMS = "datoCMS"
  CL_CLIENT_ID = "0Pc4Mll9d5GMRRl-VZhns7asNGEKtEpAKKF-fynuTfY"
  CL_ENDPOINT = "https://synthia-coorperation.commercelayer.io"
  NEXT_DATOCMS_API_TOKEN="e7ce43bf38a1c3c3f10984a25c1d15"
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
    buildEvent = "onBuild"